from typing import Protocol, TypeVar, runtime_checkable

from app.domain.models import Task, Session, WhitelistEntry, BlockedEvent

T = TypeVar("T")


@runtime_checkable
class BaseRepositoryProtocol(Protocol[T]):
    async def get_by_id(self, id: int) -> T | None: ...
    async def get_all(self) -> list[T]: ...
    async def add(self, entity: T) -> T: ...
    async def delete(self, entity: T) -> None: ...


class TaskRepositoryProtocol(BaseRepositoryProtocol[Task], Protocol):
    async def get_active(self) -> list[Task]: ...


class SessionRepositoryProtocol(BaseRepositoryProtocol[Session], Protocol):
    async def get_by_task_id(self, task_id: int) -> list[Session]: ...
    async def get_active_for_task(self, task_id: int) -> Session | None: ...


class WhitelistRepositoryProtocol(BaseRepositoryProtocol[WhitelistEntry], Protocol):
    async def get_by_task_id(self, task_id: int) -> list[WhitelistEntry]: ...
    async def delete_by_task_id(self, task_id: int) -> None: ...


class BlockedEventRepositoryProtocol(BaseRepositoryProtocol[BlockedEvent], Protocol):
    async def get_by_session_id(self, session_id: int) -> list[BlockedEvent]: ...
